// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Twenty57.Linx.Components.File
{
    using Twenty57.Linx.Plugin.Common.CodeGeneration;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class TextFileReadFieldsAndLoop_Gen : TextFileReadFieldsAndLoop_GenBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 20 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
string lengthList = "";

foreach(var field in fields.FieldList)
	lengthList+= field.Length + ",";

lengthList = lengthList.Substring(0,lengthList.Length-1);
            
            #line default
            #line hidden
            this.Write("\r\nvar fileReadX = new Twenty57.Linx.Components.File.TextFileReadX(\r\n\t");
            
            #line 28 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(filePath));
            
            #line default
            #line hidden
            this.Write(", \r\n\tTwenty57.Linx.Components.File.FileReadOptions.");
            
            #line 29 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readType));
            
            #line default
            #line hidden
            this.Write(", \r\n\tTwenty57.Linx.Components.File.TextCodepage.");
            
            #line 30 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePage));
            
            #line default
            #line hidden
            this.Write(", \r\n\t");
            
            #line 31 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(retryInterval));
            
            #line default
            #line hidden
            this.Write(", \r\n\t");
            
            #line 32 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(retryTimes));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 33 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skipHeaderLines));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 34 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skipFooterLines));
            
            #line default
            #line hidden
            this.Write(",\r\n\tTwenty57.Linx.Components.File.FileType.");
            
            #line 35 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fields.TextFileType.ToString()));
            
            #line default
            #line hidden
            this.Write(",\r\n\tTwenty57.Linx.Components.File.DelimiterType.");
            
            #line 36 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fields.Delimiter.ToString()));
            
            #line default
            #line hidden
            this.Write(",\r\n\tTwenty57.Linx.Components.File.TextQualifierType.");
            
            #line 37 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(fields.TextQualifier.ToString()));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 38 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(fields.OtherDelimiter)));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 39 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(lengthList)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\nfileReadX.InitializeLineByLine();\r\n\t\t\t\t\t\t\r\nFunc<INextResult> getNextFunctio" +
                    "n = () => \r\n{\r\n\tvar nextLine = fileReadX.Next();\r\n\tif(nextLine != null)\r\n\t{\r\n\t\tv" +
                    "ar parsedFields = fileReadX.GetValues(nextLine.LineContents);\r\n\t\tvar record = ne" +
                    "w ");
            
            #line 49 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(pathOutputTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\tvar recordInner = new ");
            
            #line 50 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordInnerTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\trecord.");
            
            #line 51 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputLineNumberName));
            
            #line default
            #line hidden
            this.Write(" = nextLine.LineNumber;\r\n\t\t");
            
            #line 52 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
 
		int index = 0;
		foreach(var field in fields.FieldList) 
		{ 
			if(!field.Skip)
			{
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif(");
            
            #line 58 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write(" < parsedFields.Length)\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 60 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
 if(field.Type.Is(typeof(DateTime)) && !String.IsNullOrWhiteSpace(field.Format)) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\trecordInner.");
            
            #line 61 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = DateTime.ParseExact(parsedFields[");
            
            #line 61 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("], \"");
            
            #line 61 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Format));
            
            #line default
            #line hidden
            this.Write("\", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTi" +
                    "meStyles.None);\r\n\t\t\t\t\t");
            
            #line 62 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\trecordInner.");
            
            #line 63 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 63 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Type.GetGeneratedType()));
            
            #line default
            #line hidden
            this.Write(")Convert.ChangeType(parsedFields[");
            
            #line 63 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("], typeof(");
            
            #line 63 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Type.GetGeneratedType()));
            
            #line default
            #line hidden
            this.Write("));\r\n\t\t\t\t\t");
            
            #line 64 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t");
            
            #line 66 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
 }
			index++;
		} 
            
            #line default
            #line hidden
            this.Write("\t\trecord.");
            
            #line 69 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(recordInnerMemberName));
            
            #line default
            #line hidden
            this.Write(" = recordInner;\r\n\t\treturn new NextResult(\r\n\t\t\t\"");
            
            #line 71 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resultsExecutionPathName));
            
            #line default
            #line hidden
            this.Write("\", \r\n\t\t\trecord);\r\n\t}\r\n\telse\r\n\t{\r\n\t\treturn null;\r\n\t}\r\n};\r\n\r\nreturn new ExecuteResu" +
                    "lt(\r\n\tnew ");
            
            #line 81 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(outputTypeName));
            
            #line default
            #line hidden
            this.Write(" { },\r\n\tgetNextFunction); \r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\murray.long\Documents\Workspace\Linx5\Components\File\Code\File\TextFileRead\TextFileReadFieldsAndLoop_Gen.tt"

private string _filePathField;

/// <summary>
/// Access the filePath parameter of the template.
/// </summary>
private string filePath
{
    get
    {
        return this._filePathField;
    }
}

private string _readTypeField;

/// <summary>
/// Access the readType parameter of the template.
/// </summary>
private string readType
{
    get
    {
        return this._readTypeField;
    }
}

private string _codePageField;

/// <summary>
/// Access the codePage parameter of the template.
/// </summary>
private string codePage
{
    get
    {
        return this._codePageField;
    }
}

private string _retryIntervalField;

/// <summary>
/// Access the retryInterval parameter of the template.
/// </summary>
private string retryInterval
{
    get
    {
        return this._retryIntervalField;
    }
}

private string _retryTimesField;

/// <summary>
/// Access the retryTimes parameter of the template.
/// </summary>
private string retryTimes
{
    get
    {
        return this._retryTimesField;
    }
}

private string _skipHeaderLinesField;

/// <summary>
/// Access the skipHeaderLines parameter of the template.
/// </summary>
private string skipHeaderLines
{
    get
    {
        return this._skipHeaderLinesField;
    }
}

private string _skipFooterLinesField;

/// <summary>
/// Access the skipFooterLines parameter of the template.
/// </summary>
private string skipFooterLines
{
    get
    {
        return this._skipFooterLinesField;
    }
}

private string _outputTypeNameField;

/// <summary>
/// Access the outputTypeName parameter of the template.
/// </summary>
private string outputTypeName
{
    get
    {
        return this._outputTypeNameField;
    }
}

private global::Twenty57.Linx.Components.File.TextFileReaderFields _fieldsField;

/// <summary>
/// Access the fields parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.File.TextFileReaderFields fields
{
    get
    {
        return this._fieldsField;
    }
}

private string _pathOutputTypeNameField;

/// <summary>
/// Access the pathOutputTypeName parameter of the template.
/// </summary>
private string pathOutputTypeName
{
    get
    {
        return this._pathOutputTypeNameField;
    }
}

private string _resultsExecutionPathNameField;

/// <summary>
/// Access the resultsExecutionPathName parameter of the template.
/// </summary>
private string resultsExecutionPathName
{
    get
    {
        return this._resultsExecutionPathNameField;
    }
}

private string _outputLineNumberNameField;

/// <summary>
/// Access the outputLineNumberName parameter of the template.
/// </summary>
private string outputLineNumberName
{
    get
    {
        return this._outputLineNumberNameField;
    }
}

private string _recordInnerTypeNameField;

/// <summary>
/// Access the recordInnerTypeName parameter of the template.
/// </summary>
private string recordInnerTypeName
{
    get
    {
        return this._recordInnerTypeNameField;
    }
}

private string _recordInnerMemberNameField;

/// <summary>
/// Access the recordInnerMemberName parameter of the template.
/// </summary>
private string recordInnerMemberName
{
    get
    {
        return this._recordInnerMemberNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool filePathValueAcquired = false;
if (this.Session.ContainsKey("filePath"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["filePath"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'filePath\' did not match the type of th" +
                "e data passed to the template.");
    }
    else
    {
        this._filePathField = ((string)(this.Session["filePath"]));
        filePathValueAcquired = true;
    }
}
if ((filePathValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("filePath");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'filePath\' did not match the type of th" +
                    "e data passed to the template.");
        }
        else
        {
            this._filePathField = ((string)(data));
        }
    }
}
bool readTypeValueAcquired = false;
if (this.Session.ContainsKey("readType"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["readType"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'readType\' did not match the type of th" +
                "e data passed to the template.");
    }
    else
    {
        this._readTypeField = ((string)(this.Session["readType"]));
        readTypeValueAcquired = true;
    }
}
if ((readTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("readType");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'readType\' did not match the type of th" +
                    "e data passed to the template.");
        }
        else
        {
            this._readTypeField = ((string)(data));
        }
    }
}
bool codePageValueAcquired = false;
if (this.Session.ContainsKey("codePage"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["codePage"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'codePage\' did not match the type of th" +
                "e data passed to the template.");
    }
    else
    {
        this._codePageField = ((string)(this.Session["codePage"]));
        codePageValueAcquired = true;
    }
}
if ((codePageValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("codePage");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'codePage\' did not match the type of th" +
                    "e data passed to the template.");
        }
        else
        {
            this._codePageField = ((string)(data));
        }
    }
}
bool retryIntervalValueAcquired = false;
if (this.Session.ContainsKey("retryInterval"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["retryInterval"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'retryInterval\' did not match the type " +
                "of the data passed to the template.");
    }
    else
    {
        this._retryIntervalField = ((string)(this.Session["retryInterval"]));
        retryIntervalValueAcquired = true;
    }
}
if ((retryIntervalValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("retryInterval");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'retryInterval\' did not match the type " +
                    "of the data passed to the template.");
        }
        else
        {
            this._retryIntervalField = ((string)(data));
        }
    }
}
bool retryTimesValueAcquired = false;
if (this.Session.ContainsKey("retryTimes"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["retryTimes"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'retryTimes\' did not match the type of " +
                "the data passed to the template.");
    }
    else
    {
        this._retryTimesField = ((string)(this.Session["retryTimes"]));
        retryTimesValueAcquired = true;
    }
}
if ((retryTimesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("retryTimes");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'retryTimes\' did not match the type of " +
                    "the data passed to the template.");
        }
        else
        {
            this._retryTimesField = ((string)(data));
        }
    }
}
bool skipHeaderLinesValueAcquired = false;
if (this.Session.ContainsKey("skipHeaderLines"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["skipHeaderLines"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'skipHeaderLines\' did not match the typ" +
                "e of the data passed to the template.");
    }
    else
    {
        this._skipHeaderLinesField = ((string)(this.Session["skipHeaderLines"]));
        skipHeaderLinesValueAcquired = true;
    }
}
if ((skipHeaderLinesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("skipHeaderLines");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'skipHeaderLines\' did not match the typ" +
                    "e of the data passed to the template.");
        }
        else
        {
            this._skipHeaderLinesField = ((string)(data));
        }
    }
}
bool skipFooterLinesValueAcquired = false;
if (this.Session.ContainsKey("skipFooterLines"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["skipFooterLines"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'skipFooterLines\' did not match the typ" +
                "e of the data passed to the template.");
    }
    else
    {
        this._skipFooterLinesField = ((string)(this.Session["skipFooterLines"]));
        skipFooterLinesValueAcquired = true;
    }
}
if ((skipFooterLinesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("skipFooterLines");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'skipFooterLines\' did not match the typ" +
                    "e of the data passed to the template.");
        }
        else
        {
            this._skipFooterLinesField = ((string)(data));
        }
    }
}
bool outputTypeNameValueAcquired = false;
if (this.Session.ContainsKey("outputTypeName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["outputTypeName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'outputTypeName\' did not match the type" +
                " of the data passed to the template.");
    }
    else
    {
        this._outputTypeNameField = ((string)(this.Session["outputTypeName"]));
        outputTypeNameValueAcquired = true;
    }
}
if ((outputTypeNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("outputTypeName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'outputTypeName\' did not match the type" +
                    " of the data passed to the template.");
        }
        else
        {
            this._outputTypeNameField = ((string)(data));
        }
    }
}
bool fieldsValueAcquired = false;
if (this.Session.ContainsKey("fields"))
{
    if ((typeof(global::Twenty57.Linx.Components.File.TextFileReaderFields).IsAssignableFrom(this.Session["fields"].GetType()) == false))
    {
        this.Error("The type \'Twenty57.Linx.Components.File.TextFileReaderFields\' of the parameter \'f" +
                "ields\' did not match the type of the data passed to the template.");
    }
    else
    {
        this._fieldsField = ((global::Twenty57.Linx.Components.File.TextFileReaderFields)(this.Session["fields"]));
        fieldsValueAcquired = true;
    }
}
if ((fieldsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("fields");
    if ((data != null))
    {
        if ((typeof(global::Twenty57.Linx.Components.File.TextFileReaderFields).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'Twenty57.Linx.Components.File.TextFileReaderFields\' of the parameter \'f" +
                    "ields\' did not match the type of the data passed to the template.");
        }
        else
        {
            this._fieldsField = ((global::Twenty57.Linx.Components.File.TextFileReaderFields)(data));
        }
    }
}
bool pathOutputTypeNameValueAcquired = false;
if (this.Session.ContainsKey("pathOutputTypeName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["pathOutputTypeName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'pathOutputTypeName\' did not match the " +
                "type of the data passed to the template.");
    }
    else
    {
        this._pathOutputTypeNameField = ((string)(this.Session["pathOutputTypeName"]));
        pathOutputTypeNameValueAcquired = true;
    }
}
if ((pathOutputTypeNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("pathOutputTypeName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'pathOutputTypeName\' did not match the " +
                    "type of the data passed to the template.");
        }
        else
        {
            this._pathOutputTypeNameField = ((string)(data));
        }
    }
}
bool resultsExecutionPathNameValueAcquired = false;
if (this.Session.ContainsKey("resultsExecutionPathName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["resultsExecutionPathName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'resultsExecutionPathName\' did not matc" +
                "h the type of the data passed to the template.");
    }
    else
    {
        this._resultsExecutionPathNameField = ((string)(this.Session["resultsExecutionPathName"]));
        resultsExecutionPathNameValueAcquired = true;
    }
}
if ((resultsExecutionPathNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("resultsExecutionPathName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'resultsExecutionPathName\' did not matc" +
                    "h the type of the data passed to the template.");
        }
        else
        {
            this._resultsExecutionPathNameField = ((string)(data));
        }
    }
}
bool outputLineNumberNameValueAcquired = false;
if (this.Session.ContainsKey("outputLineNumberName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["outputLineNumberName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'outputLineNumberName\' did not match th" +
                "e type of the data passed to the template.");
    }
    else
    {
        this._outputLineNumberNameField = ((string)(this.Session["outputLineNumberName"]));
        outputLineNumberNameValueAcquired = true;
    }
}
if ((outputLineNumberNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("outputLineNumberName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'outputLineNumberName\' did not match th" +
                    "e type of the data passed to the template.");
        }
        else
        {
            this._outputLineNumberNameField = ((string)(data));
        }
    }
}
bool recordInnerTypeNameValueAcquired = false;
if (this.Session.ContainsKey("recordInnerTypeName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["recordInnerTypeName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'recordInnerTypeName\' did not match the" +
                " type of the data passed to the template.");
    }
    else
    {
        this._recordInnerTypeNameField = ((string)(this.Session["recordInnerTypeName"]));
        recordInnerTypeNameValueAcquired = true;
    }
}
if ((recordInnerTypeNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("recordInnerTypeName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'recordInnerTypeName\' did not match the" +
                    " type of the data passed to the template.");
        }
        else
        {
            this._recordInnerTypeNameField = ((string)(data));
        }
    }
}
bool recordInnerMemberNameValueAcquired = false;
if (this.Session.ContainsKey("recordInnerMemberName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["recordInnerMemberName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'recordInnerMemberName\' did not match t" +
                "he type of the data passed to the template.");
    }
    else
    {
        this._recordInnerMemberNameField = ((string)(this.Session["recordInnerMemberName"]));
        recordInnerMemberNameValueAcquired = true;
    }
}
if ((recordInnerMemberNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("recordInnerMemberName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'recordInnerMemberName\' did not match t" +
                    "he type of the data passed to the template.");
        }
        else
        {
            this._recordInnerMemberNameField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class TextFileReadFieldsAndLoop_GenBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
