// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Twenty57.Linx.Components.Database.DbBulkCopy
{
    using Twenty57.Linx.Plugin.Common.CodeGeneration;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class DbBulkCopy_Gen : DbBulkCopy_GenBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n\r\nvar bulkCopier = new Twenty57.Linx.Components.Database.DbBulkCopy.Runtime.DbB" +
                    "ulkCopierX(\r\n\t");
            
            #line 19 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.EnumAsString(ConnectionType)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 19 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConnectionStringProperty));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 19 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(TableName)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 foreach (var nextColumnName in ColumnNames) { 
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 21 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(nextColumnName)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 22 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write(");\r\nbulkCopier.Timeout = ");
            
            #line 23 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Timeout));
            
            #line default
            #line hidden
            this.Write(";\r\nbulkCopier.BatchSize = ");
            
            #line 24 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BatchSize));
            
            #line default
            #line hidden
            this.Write(";\r\nbulkCopier.LogEvent += message => ");
            
            #line 25 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FunctionContextProperty));
            
            #line default
            #line hidden
            this.Write(".Log(message);\r\n\r\nvar makeRow = new System.Func<dynamic, object[]>(row => {\r\n\tobj" +
                    "ect[] columns = new object[");
            
            #line 28 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColumnPropertyNames.Length));
            
            #line default
            #line hidden
            this.Write("];\r\n\t");
            
            #line 29 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 for (int i = 0; i < ColumnPropertyNames.Length; i++) { 
            
            #line default
            #line hidden
            this.Write("\tcolumns[");
            
            #line 30 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("] = \r\n\t\t");
            
            #line 31 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 if (ColumnDataTypes[i] == Twenty57.Linx.Components.Database.Common.DatabaseModel.DataType.Binary) { 
            
            #line default
            #line hidden
            this.Write("\t\trow.");
            
            #line 32 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColumnPropertyNames[i]));
            
            #line default
            #line hidden
            this.Write(" == null ? null : row.");
            
            #line 32 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColumnPropertyNames[i]));
            
            #line default
            #line hidden
            this.Write(".ToArray();\r\n\t\t");
            
            #line 33 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\trow.");
            
            #line 34 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ColumnPropertyNames[i]));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t");
            
            #line 35 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 36 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\treturn columns;\r\n});\r\n\r\nbulkCopier.Start();\r\n");
            
            #line 41 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExecutionPathOutputName));
            
            #line default
            #line hidden
            this.Write(" = Twenty57.Linx.Components.Database.DbBulkCopy.Runtime.SingleEnumerable.Make(\r\n\t" +
                    "new Twenty57.Linx.Components.Database.DbBulkCopy.Runtime.Loader(bulkCopier, make" +
                    "Row))\r\n\t.Select(l => new Twenty57.Linx.Plugin.Common.CodeGeneration.NextResult(");
            
            #line 43 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(ExecutionPathName)));
            
            #line default
            #line hidden
            this.Write(", l));\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Hg\Linx5 Components\Database\Code\Database\DbBulkCopy\DbBulkCopy_Gen.tt"

private string _FunctionContextPropertyField;

/// <summary>
/// Access the FunctionContextProperty parameter of the template.
/// </summary>
private string FunctionContextProperty
{
    get
    {
        return this._FunctionContextPropertyField;
    }
}

private global::Twenty57.Linx.Components.Database.Common.ConnectionType _ConnectionTypeField;

/// <summary>
/// Access the ConnectionType parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.Database.Common.ConnectionType ConnectionType
{
    get
    {
        return this._ConnectionTypeField;
    }
}

private string _ConnectionStringPropertyField;

/// <summary>
/// Access the ConnectionStringProperty parameter of the template.
/// </summary>
private string ConnectionStringProperty
{
    get
    {
        return this._ConnectionStringPropertyField;
    }
}

private int _TimeoutField;

/// <summary>
/// Access the Timeout parameter of the template.
/// </summary>
private int Timeout
{
    get
    {
        return this._TimeoutField;
    }
}

private int _BatchSizeField;

/// <summary>
/// Access the BatchSize parameter of the template.
/// </summary>
private int BatchSize
{
    get
    {
        return this._BatchSizeField;
    }
}

private string _TableNameField;

/// <summary>
/// Access the TableName parameter of the template.
/// </summary>
private string TableName
{
    get
    {
        return this._TableNameField;
    }
}

private string[] _ColumnNamesField;

/// <summary>
/// Access the ColumnNames parameter of the template.
/// </summary>
private string[] ColumnNames
{
    get
    {
        return this._ColumnNamesField;
    }
}

private string[] _ColumnPropertyNamesField;

/// <summary>
/// Access the ColumnPropertyNames parameter of the template.
/// </summary>
private string[] ColumnPropertyNames
{
    get
    {
        return this._ColumnPropertyNamesField;
    }
}

private Twenty57.Linx.Components.Database.Common.DatabaseModel.DataType[] _ColumnDataTypesField;

/// <summary>
/// Access the ColumnDataTypes parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.Database.Common.DatabaseModel.DataType[] ColumnDataTypes
{
    get
    {
        return this._ColumnDataTypesField;
    }
}

private string _ExecutionPathOutputNameField;

/// <summary>
/// Access the ExecutionPathOutputName parameter of the template.
/// </summary>
private string ExecutionPathOutputName
{
    get
    {
        return this._ExecutionPathOutputNameField;
    }
}

private string _ExecutionPathNameField;

/// <summary>
/// Access the ExecutionPathName parameter of the template.
/// </summary>
private string ExecutionPathName
{
    get
    {
        return this._ExecutionPathNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool FunctionContextPropertyValueAcquired = false;
if (this.Session.ContainsKey("FunctionContextProperty"))
{
    this._FunctionContextPropertyField = ((string)(this.Session["FunctionContextProperty"]));
    FunctionContextPropertyValueAcquired = true;
}
if ((FunctionContextPropertyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FunctionContextProperty");
    if ((data != null))
    {
        this._FunctionContextPropertyField = ((string)(data));
    }
}
bool ConnectionTypeValueAcquired = false;
if (this.Session.ContainsKey("ConnectionType"))
{
    this._ConnectionTypeField = ((global::Twenty57.Linx.Components.Database.Common.ConnectionType)(this.Session["ConnectionType"]));
    ConnectionTypeValueAcquired = true;
}
if ((ConnectionTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionType");
    if ((data != null))
    {
        this._ConnectionTypeField = ((global::Twenty57.Linx.Components.Database.Common.ConnectionType)(data));
    }
}
bool ConnectionStringPropertyValueAcquired = false;
if (this.Session.ContainsKey("ConnectionStringProperty"))
{
    this._ConnectionStringPropertyField = ((string)(this.Session["ConnectionStringProperty"]));
    ConnectionStringPropertyValueAcquired = true;
}
if ((ConnectionStringPropertyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionStringProperty");
    if ((data != null))
    {
        this._ConnectionStringPropertyField = ((string)(data));
    }
}
bool TimeoutValueAcquired = false;
if (this.Session.ContainsKey("Timeout"))
{
    this._TimeoutField = ((int)(this.Session["Timeout"]));
    TimeoutValueAcquired = true;
}
if ((TimeoutValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Timeout");
    if ((data != null))
    {
        this._TimeoutField = ((int)(data));
    }
}
bool BatchSizeValueAcquired = false;
if (this.Session.ContainsKey("BatchSize"))
{
    this._BatchSizeField = ((int)(this.Session["BatchSize"]));
    BatchSizeValueAcquired = true;
}
if ((BatchSizeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("BatchSize");
    if ((data != null))
    {
        this._BatchSizeField = ((int)(data));
    }
}
bool TableNameValueAcquired = false;
if (this.Session.ContainsKey("TableName"))
{
    this._TableNameField = ((string)(this.Session["TableName"]));
    TableNameValueAcquired = true;
}
if ((TableNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TableName");
    if ((data != null))
    {
        this._TableNameField = ((string)(data));
    }
}
bool ColumnNamesValueAcquired = false;
if (this.Session.ContainsKey("ColumnNames"))
{
    this._ColumnNamesField = ((string[])(this.Session["ColumnNames"]));
    ColumnNamesValueAcquired = true;
}
if ((ColumnNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ColumnNames");
    if ((data != null))
    {
        this._ColumnNamesField = ((string[])(data));
    }
}
bool ColumnPropertyNamesValueAcquired = false;
if (this.Session.ContainsKey("ColumnPropertyNames"))
{
    this._ColumnPropertyNamesField = ((string[])(this.Session["ColumnPropertyNames"]));
    ColumnPropertyNamesValueAcquired = true;
}
if ((ColumnPropertyNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ColumnPropertyNames");
    if ((data != null))
    {
        this._ColumnPropertyNamesField = ((string[])(data));
    }
}
bool ColumnDataTypesValueAcquired = false;
if (this.Session.ContainsKey("ColumnDataTypes"))
{
    this._ColumnDataTypesField = ((global::Twenty57.Linx.Components.Database.Common.DatabaseModel.DataType[])(this.Session["ColumnDataTypes"]));
    ColumnDataTypesValueAcquired = true;
}
if ((ColumnDataTypesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ColumnDataTypes");
    if ((data != null))
    {
        this._ColumnDataTypesField = ((global::Twenty57.Linx.Components.Database.Common.DatabaseModel.DataType[])(data));
    }
}
bool ExecutionPathOutputNameValueAcquired = false;
if (this.Session.ContainsKey("ExecutionPathOutputName"))
{
    this._ExecutionPathOutputNameField = ((string)(this.Session["ExecutionPathOutputName"]));
    ExecutionPathOutputNameValueAcquired = true;
}
if ((ExecutionPathOutputNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ExecutionPathOutputName");
    if ((data != null))
    {
        this._ExecutionPathOutputNameField = ((string)(data));
    }
}
bool ExecutionPathNameValueAcquired = false;
if (this.Session.ContainsKey("ExecutionPathName"))
{
    this._ExecutionPathNameField = ((string)(this.Session["ExecutionPathName"]));
    ExecutionPathNameValueAcquired = true;
}
if ((ExecutionPathNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ExecutionPathName");
    if ((data != null))
    {
        this._ExecutionPathNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class DbBulkCopy_GenBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
