// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Twenty57.Linx.Components.Database.ExecuteSQL
{
    using System.Linq;
    using Twenty57.Linx.Plugin.Common.CodeGeneration;
    using Twenty57.Linx.Components.Database.ExecuteSQL;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class ExecuteSQL_Gen : ExecuteSQL_GenBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\nvar OutputNames = ");
            
            #line 23 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ArrayAsString(ResultTypeFields.Select(x => x.Name))));
            
            #line default
            #line hidden
            this.Write(";\r\nvar ColumnNames = ");
            
            #line 24 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ArrayAsString(ResultTypeFields.Select(x => x.ColumnName))));
            
            #line default
            #line hidden
            this.Write(";\r\nvar SqlIdentifiers = ");
            
            #line 25 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SqlIdentifiers));
            
            #line default
            #line hidden
            this.Write(";\r\nvar SqlValues = ");
            
            #line 26 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SqlValues));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nvar executeSqlX = new Twenty57.Linx.Components.Database.ExecuteSQL.ExecuteSQ" +
                    "LX(\r\n");
            
            #line 29 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 if (UseTransaction) { 
            
            #line default
            #line hidden
            
            #line 30 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TransactionProperty));
            
            #line default
            #line hidden
            this.Write(".GetConnectionType(), ");
            
            #line 30 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TransactionProperty));
            
            #line default
            #line hidden
            this.Write(".GetDbTransaction(), \r\n");
            
            #line 31 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 32 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.EnumAsString(ConnectionType)));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 32 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConnectionStringProperty));
            
            #line default
            #line hidden
            this.Write(", \r\n");
            
            #line 33 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } 
            
            #line default
            #line hidden
            
            #line 34 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Timeout));
            
            #line default
            #line hidden
            this.Write(", OutputNames, ColumnNames, ");
            
            #line 34 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Sql));
            
            #line default
            #line hidden
            this.Write(", SqlIdentifiers, SqlValues);\r\nexecuteSqlX.LogEvent += message => ");
            
            #line 35 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FunctionContextProperty));
            
            #line default
            #line hidden
            this.Write(".Log(message);\r\n\r\n");
            
            #line 37 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 if (RowType != null) { 
            
            #line default
            #line hidden
            this.Write("\r\nvar rowBuilder = new System.Func<");
            
            #line 39 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RowTypeName));
            
            #line default
            #line hidden
            this.Write(">(() => {\r\n\t");
            
            #line 40 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 var rowFields = ResultTypeFields.Where(f => !string.IsNullOrEmpty(f.Name));
	var logFormatString = "Retrieved "; 
	int index = 0;
	foreach (var nextField in rowFields)
		logFormatString += string.Format("{0} = {{{1}}}, ", nextField.ColumnName, index++);
	
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 46 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FunctionContextProperty));
            
            #line default
            #line hidden
            this.Write(".Log(System.String.Format(");
            
            #line 46 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(logFormatString.TrimEnd(',', ' '))));
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 47 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 foreach (var nextField in rowFields) { 
            
            #line default
            #line hidden
            this.Write("\t\t, Twenty57.Linx.Components.Database.Common.LogHelpers.GetDisplayString(executeS" +
                    "qlX.Reader[");
            
            #line 48 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(nextField.ColumnName)));
            
            #line default
            #line hidden
            this.Write("])\r\n\t");
            
            #line 49 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t));\r\n\r\n\treturn new ");
            
            #line 52 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RowTypeName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t");
            
            #line 54 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 foreach (var nextField in rowFields) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 55 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParamName(nextField.Name)));
            
            #line default
            #line hidden
            this.Write(" = Twenty57.Linx.Components.Database.ExecuteSQL.DatabaseHelpers.CheckDbValue<");
            
            #line 55 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Twenty57.Linx.Components.Database.Common.TypeHelpers.GetCodeStringForType(nextField.TypeReference)));
            
            #line default
            #line hidden
            this.Write(">(executeSqlX.Reader[");
            
            #line 55 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(nextField.ColumnName)));
            
            #line default
            #line hidden
            this.Write("]), \r\n\t\t");
            
            #line 56 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t};\r\n});\r\n\r\n");
            
            #line 60 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 if (ReturnMode == ExecuteSQLShared.ReturnModeType.ListOfRows) { 
            
            #line default
            #line hidden
            this.Write("try\r\n{\r\n\texecuteSqlX.OpenReader();\r\n\r\n\tvar table = new List<");
            
            #line 65 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RowTypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\twhile (executeSqlX.Reader.Read())\r\n\t\ttable.Add(rowBuilder());\r\n\treturn tab" +
                    "le;\r\n}\r\nfinally\r\n{\r\n\texecuteSqlX.Dispose();\r\n}\r\n");
            
            #line 74 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } else if ((ReturnMode == ExecuteSQLShared.ReturnModeType.FirstRow) || (ReturnMode == ExecuteSQLShared.ReturnModeType.FirstRowElseEmptyRow)) { 
            
            #line default
            #line hidden
            this.Write("try\r\n{\r\n\texecuteSqlX.OpenReader();\r\n\r\n\t");
            
            #line 79 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RowTypeName));
            
            #line default
            #line hidden
            this.Write(" row;\r\n\tif (executeSqlX.Reader.Read())\r\n\t\trow = rowBuilder();\r\n\telse\r\n\t{\r\n\t\t");
            
            #line 84 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 if (ReturnMode == ExecuteSQLShared.ReturnModeType.FirstRow) { 
            
            #line default
            #line hidden
            this.Write("\t\tthrow new Exception(\"No rows returned by query.\");\r\n\t\t");
            
            #line 86 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\trow = new ");
            
            #line 87 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RowTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t");
            
            #line 88 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\treturn row;\r\n}\r\nfinally\r\n{\r\n\texecuteSqlX.Dispose();\r\n}\r\n");
            
            #line 97 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("executeSqlX.OpenReader();\r\n");
            
            #line 99 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExecutionPathOutputName));
            
            #line default
            #line hidden
            this.Write(" = \r\nexecuteSqlX.Rows<Twenty57.Linx.Plugin.Common.CodeGeneration.NextResult>(read" +
                    "er => {\r\n\tvar row = rowBuilder();\r\n\treturn new Twenty57.Linx.Plugin.Common.CodeG" +
                    "eneration.NextResult(\"");
            
            #line 102 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExecutionPathName));
            
            #line default
            #line hidden
            this.Write("\", row);\r\n});\r\n");
            
            #line 104 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } 
            
            #line default
            #line hidden
            
            #line 105 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("try\r\n{\r\n\texecuteSqlX.OpenReader();\r\n}\r\nfinally\r\n{\r\n\texecuteSqlX.Dispose();\r\n}\r\n");
            
            #line 114 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Hg\Linx5 Components\Database\Code\Database\ExecuteSQL\ExecuteSQL_Gen.tt"

private string _FunctionContextPropertyField;

/// <summary>
/// Access the FunctionContextProperty parameter of the template.
/// </summary>
private string FunctionContextProperty
{
    get
    {
        return this._FunctionContextPropertyField;
    }
}

private global::System.Func<string, string> _GetParamNameField;

/// <summary>
/// Access the GetParamName parameter of the template.
/// </summary>
private global::System.Func<string, string> GetParamName
{
    get
    {
        return this._GetParamNameField;
    }
}

private int _TimeoutField;

/// <summary>
/// Access the Timeout parameter of the template.
/// </summary>
private int Timeout
{
    get
    {
        return this._TimeoutField;
    }
}

private bool _UseTransactionField;

/// <summary>
/// Access the UseTransaction parameter of the template.
/// </summary>
private bool UseTransaction
{
    get
    {
        return this._UseTransactionField;
    }
}

private string _TransactionPropertyField;

/// <summary>
/// Access the TransactionProperty parameter of the template.
/// </summary>
private string TransactionProperty
{
    get
    {
        return this._TransactionPropertyField;
    }
}

private global::Twenty57.Linx.Components.Database.Common.ConnectionType _ConnectionTypeField;

/// <summary>
/// Access the ConnectionType parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.Database.Common.ConnectionType ConnectionType
{
    get
    {
        return this._ConnectionTypeField;
    }
}

private string _ConnectionStringPropertyField;

/// <summary>
/// Access the ConnectionStringProperty parameter of the template.
/// </summary>
private string ConnectionStringProperty
{
    get
    {
        return this._ConnectionStringPropertyField;
    }
}

private string _SqlField;

/// <summary>
/// Access the Sql parameter of the template.
/// </summary>
private string Sql
{
    get
    {
        return this._SqlField;
    }
}

private global::Twenty57.Linx.Components.Database.ExecuteSQL.ExecuteSQLShared.ReturnModeType _ReturnModeField;

/// <summary>
/// Access the ReturnMode parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.Database.ExecuteSQL.ExecuteSQLShared.ReturnModeType ReturnMode
{
    get
    {
        return this._ReturnModeField;
    }
}

private string _SqlIdentifiersField;

/// <summary>
/// Access the SqlIdentifiers parameter of the template.
/// </summary>
private string SqlIdentifiers
{
    get
    {
        return this._SqlIdentifiersField;
    }
}

private string _SqlValuesField;

/// <summary>
/// Access the SqlValues parameter of the template.
/// </summary>
private string SqlValues
{
    get
    {
        return this._SqlValuesField;
    }
}

private global::Twenty57.Linx.Components.Database.ExecuteSQL.ResultTypeFields _ResultTypeFieldsField;

/// <summary>
/// Access the ResultTypeFields parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.Database.ExecuteSQL.ResultTypeFields ResultTypeFields
{
    get
    {
        return this._ResultTypeFieldsField;
    }
}

private global::Twenty57.Linx.Plugin.Common.ITypeReference _RowTypeField;

/// <summary>
/// Access the RowType parameter of the template.
/// </summary>
private global::Twenty57.Linx.Plugin.Common.ITypeReference RowType
{
    get
    {
        return this._RowTypeField;
    }
}

private string _RowTypeNameField;

/// <summary>
/// Access the RowTypeName parameter of the template.
/// </summary>
private string RowTypeName
{
    get
    {
        return this._RowTypeNameField;
    }
}

private string _ExecutionPathNameField;

/// <summary>
/// Access the ExecutionPathName parameter of the template.
/// </summary>
private string ExecutionPathName
{
    get
    {
        return this._ExecutionPathNameField;
    }
}

private string _ExecutionPathOutputNameField;

/// <summary>
/// Access the ExecutionPathOutputName parameter of the template.
/// </summary>
private string ExecutionPathOutputName
{
    get
    {
        return this._ExecutionPathOutputNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool FunctionContextPropertyValueAcquired = false;
if (this.Session.ContainsKey("FunctionContextProperty"))
{
    this._FunctionContextPropertyField = ((string)(this.Session["FunctionContextProperty"]));
    FunctionContextPropertyValueAcquired = true;
}
if ((FunctionContextPropertyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FunctionContextProperty");
    if ((data != null))
    {
        this._FunctionContextPropertyField = ((string)(data));
    }
}
bool GetParamNameValueAcquired = false;
if (this.Session.ContainsKey("GetParamName"))
{
    this._GetParamNameField = ((global::System.Func<string, string>)(this.Session["GetParamName"]));
    GetParamNameValueAcquired = true;
}
if ((GetParamNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GetParamName");
    if ((data != null))
    {
        this._GetParamNameField = ((global::System.Func<string, string>)(data));
    }
}
bool TimeoutValueAcquired = false;
if (this.Session.ContainsKey("Timeout"))
{
    this._TimeoutField = ((int)(this.Session["Timeout"]));
    TimeoutValueAcquired = true;
}
if ((TimeoutValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Timeout");
    if ((data != null))
    {
        this._TimeoutField = ((int)(data));
    }
}
bool UseTransactionValueAcquired = false;
if (this.Session.ContainsKey("UseTransaction"))
{
    this._UseTransactionField = ((bool)(this.Session["UseTransaction"]));
    UseTransactionValueAcquired = true;
}
if ((UseTransactionValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UseTransaction");
    if ((data != null))
    {
        this._UseTransactionField = ((bool)(data));
    }
}
bool TransactionPropertyValueAcquired = false;
if (this.Session.ContainsKey("TransactionProperty"))
{
    this._TransactionPropertyField = ((string)(this.Session["TransactionProperty"]));
    TransactionPropertyValueAcquired = true;
}
if ((TransactionPropertyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("TransactionProperty");
    if ((data != null))
    {
        this._TransactionPropertyField = ((string)(data));
    }
}
bool ConnectionTypeValueAcquired = false;
if (this.Session.ContainsKey("ConnectionType"))
{
    this._ConnectionTypeField = ((global::Twenty57.Linx.Components.Database.Common.ConnectionType)(this.Session["ConnectionType"]));
    ConnectionTypeValueAcquired = true;
}
if ((ConnectionTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionType");
    if ((data != null))
    {
        this._ConnectionTypeField = ((global::Twenty57.Linx.Components.Database.Common.ConnectionType)(data));
    }
}
bool ConnectionStringPropertyValueAcquired = false;
if (this.Session.ContainsKey("ConnectionStringProperty"))
{
    this._ConnectionStringPropertyField = ((string)(this.Session["ConnectionStringProperty"]));
    ConnectionStringPropertyValueAcquired = true;
}
if ((ConnectionStringPropertyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionStringProperty");
    if ((data != null))
    {
        this._ConnectionStringPropertyField = ((string)(data));
    }
}
bool SqlValueAcquired = false;
if (this.Session.ContainsKey("Sql"))
{
    this._SqlField = ((string)(this.Session["Sql"]));
    SqlValueAcquired = true;
}
if ((SqlValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Sql");
    if ((data != null))
    {
        this._SqlField = ((string)(data));
    }
}
bool ReturnModeValueAcquired = false;
if (this.Session.ContainsKey("ReturnMode"))
{
    this._ReturnModeField = ((global::Twenty57.Linx.Components.Database.ExecuteSQL.ExecuteSQLShared.ReturnModeType)(this.Session["ReturnMode"]));
    ReturnModeValueAcquired = true;
}
if ((ReturnModeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ReturnMode");
    if ((data != null))
    {
        this._ReturnModeField = ((global::Twenty57.Linx.Components.Database.ExecuteSQL.ExecuteSQLShared.ReturnModeType)(data));
    }
}
bool SqlIdentifiersValueAcquired = false;
if (this.Session.ContainsKey("SqlIdentifiers"))
{
    this._SqlIdentifiersField = ((string)(this.Session["SqlIdentifiers"]));
    SqlIdentifiersValueAcquired = true;
}
if ((SqlIdentifiersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("SqlIdentifiers");
    if ((data != null))
    {
        this._SqlIdentifiersField = ((string)(data));
    }
}
bool SqlValuesValueAcquired = false;
if (this.Session.ContainsKey("SqlValues"))
{
    this._SqlValuesField = ((string)(this.Session["SqlValues"]));
    SqlValuesValueAcquired = true;
}
if ((SqlValuesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("SqlValues");
    if ((data != null))
    {
        this._SqlValuesField = ((string)(data));
    }
}
bool ResultTypeFieldsValueAcquired = false;
if (this.Session.ContainsKey("ResultTypeFields"))
{
    this._ResultTypeFieldsField = ((global::Twenty57.Linx.Components.Database.ExecuteSQL.ResultTypeFields)(this.Session["ResultTypeFields"]));
    ResultTypeFieldsValueAcquired = true;
}
if ((ResultTypeFieldsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ResultTypeFields");
    if ((data != null))
    {
        this._ResultTypeFieldsField = ((global::Twenty57.Linx.Components.Database.ExecuteSQL.ResultTypeFields)(data));
    }
}
bool RowTypeValueAcquired = false;
if (this.Session.ContainsKey("RowType"))
{
    this._RowTypeField = ((global::Twenty57.Linx.Plugin.Common.ITypeReference)(this.Session["RowType"]));
    RowTypeValueAcquired = true;
}
if ((RowTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RowType");
    if ((data != null))
    {
        this._RowTypeField = ((global::Twenty57.Linx.Plugin.Common.ITypeReference)(data));
    }
}
bool RowTypeNameValueAcquired = false;
if (this.Session.ContainsKey("RowTypeName"))
{
    this._RowTypeNameField = ((string)(this.Session["RowTypeName"]));
    RowTypeNameValueAcquired = true;
}
if ((RowTypeNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RowTypeName");
    if ((data != null))
    {
        this._RowTypeNameField = ((string)(data));
    }
}
bool ExecutionPathNameValueAcquired = false;
if (this.Session.ContainsKey("ExecutionPathName"))
{
    this._ExecutionPathNameField = ((string)(this.Session["ExecutionPathName"]));
    ExecutionPathNameValueAcquired = true;
}
if ((ExecutionPathNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ExecutionPathName");
    if ((data != null))
    {
        this._ExecutionPathNameField = ((string)(data));
    }
}
bool ExecutionPathOutputNameValueAcquired = false;
if (this.Session.ContainsKey("ExecutionPathOutputName"))
{
    this._ExecutionPathOutputNameField = ((string)(this.Session["ExecutionPathOutputName"]));
    ExecutionPathOutputNameValueAcquired = true;
}
if ((ExecutionPathOutputNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ExecutionPathOutputName");
    if ((data != null))
    {
        this._ExecutionPathOutputNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class ExecuteSQL_GenBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
