// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Twenty57.Linx.Components.Database.BeginTransaction
{
    using Twenty57.Linx.Plugin.Common.CodeGeneration;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class BeginTransaction_Gen : BeginTransaction_GenBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\nvar beginTransactionX = new Twenty57.Linx.Components.Database.BeginTransaction." +
                    "BeginTransactionX(\r\n\t");
            
            #line 12 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.EnumAsString(ConnectionType)));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 13 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConnectionStringPropertyName));
            
            #line default
            #line hidden
            this.Write(",\r\n\tSystem.Data.IsolationLevel.");
            
            #line 14 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IsolationLevelName));
            
            #line default
            #line hidden
            this.Write(");\r\nbeginTransactionX.Transaction.LogEvent += message => ");
            
            #line 15 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FunctionContextProperty));
            
            #line default
            #line hidden
            this.Write(".Log(message);\r\n");
            
            #line 16 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ExecutionPathOutputName));
            
            #line default
            #line hidden
            this.Write(" = beginTransactionX.Select(transaction => new Twenty57.Linx.Plugin.Common.CodeGe" +
                    "neration.NextResult(");
            
            #line 16 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CSharpUtilities.ToVerbatimString(ExecutionPathName)));
            
            #line default
            #line hidden
            this.Write(", transaction));\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Hg\Linx5 Components\Database\Code\Database\BeginTransaction\BeginTransaction_Gen.tt"

private string _FunctionContextPropertyField;

/// <summary>
/// Access the FunctionContextProperty parameter of the template.
/// </summary>
private string FunctionContextProperty
{
    get
    {
        return this._FunctionContextPropertyField;
    }
}

private global::Twenty57.Linx.Components.Database.Common.ConnectionType _ConnectionTypeField;

/// <summary>
/// Access the ConnectionType parameter of the template.
/// </summary>
private global::Twenty57.Linx.Components.Database.Common.ConnectionType ConnectionType
{
    get
    {
        return this._ConnectionTypeField;
    }
}

private string _ConnectionStringPropertyNameField;

/// <summary>
/// Access the ConnectionStringPropertyName parameter of the template.
/// </summary>
private string ConnectionStringPropertyName
{
    get
    {
        return this._ConnectionStringPropertyNameField;
    }
}

private string _IsolationLevelNameField;

/// <summary>
/// Access the IsolationLevelName parameter of the template.
/// </summary>
private string IsolationLevelName
{
    get
    {
        return this._IsolationLevelNameField;
    }
}

private string _ExecutionPathNameField;

/// <summary>
/// Access the ExecutionPathName parameter of the template.
/// </summary>
private string ExecutionPathName
{
    get
    {
        return this._ExecutionPathNameField;
    }
}

private string _ExecutionPathOutputNameField;

/// <summary>
/// Access the ExecutionPathOutputName parameter of the template.
/// </summary>
private string ExecutionPathOutputName
{
    get
    {
        return this._ExecutionPathOutputNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool FunctionContextPropertyValueAcquired = false;
if (this.Session.ContainsKey("FunctionContextProperty"))
{
    this._FunctionContextPropertyField = ((string)(this.Session["FunctionContextProperty"]));
    FunctionContextPropertyValueAcquired = true;
}
if ((FunctionContextPropertyValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FunctionContextProperty");
    if ((data != null))
    {
        this._FunctionContextPropertyField = ((string)(data));
    }
}
bool ConnectionTypeValueAcquired = false;
if (this.Session.ContainsKey("ConnectionType"))
{
    this._ConnectionTypeField = ((global::Twenty57.Linx.Components.Database.Common.ConnectionType)(this.Session["ConnectionType"]));
    ConnectionTypeValueAcquired = true;
}
if ((ConnectionTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionType");
    if ((data != null))
    {
        this._ConnectionTypeField = ((global::Twenty57.Linx.Components.Database.Common.ConnectionType)(data));
    }
}
bool ConnectionStringPropertyNameValueAcquired = false;
if (this.Session.ContainsKey("ConnectionStringPropertyName"))
{
    this._ConnectionStringPropertyNameField = ((string)(this.Session["ConnectionStringPropertyName"]));
    ConnectionStringPropertyNameValueAcquired = true;
}
if ((ConnectionStringPropertyNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ConnectionStringPropertyName");
    if ((data != null))
    {
        this._ConnectionStringPropertyNameField = ((string)(data));
    }
}
bool IsolationLevelNameValueAcquired = false;
if (this.Session.ContainsKey("IsolationLevelName"))
{
    this._IsolationLevelNameField = ((string)(this.Session["IsolationLevelName"]));
    IsolationLevelNameValueAcquired = true;
}
if ((IsolationLevelNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IsolationLevelName");
    if ((data != null))
    {
        this._IsolationLevelNameField = ((string)(data));
    }
}
bool ExecutionPathNameValueAcquired = false;
if (this.Session.ContainsKey("ExecutionPathName"))
{
    this._ExecutionPathNameField = ((string)(this.Session["ExecutionPathName"]));
    ExecutionPathNameValueAcquired = true;
}
if ((ExecutionPathNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ExecutionPathName");
    if ((data != null))
    {
        this._ExecutionPathNameField = ((string)(data));
    }
}
bool ExecutionPathOutputNameValueAcquired = false;
if (this.Session.ContainsKey("ExecutionPathOutputName"))
{
    this._ExecutionPathOutputNameField = ((string)(this.Session["ExecutionPathOutputName"]));
    ExecutionPathOutputNameValueAcquired = true;
}
if ((ExecutionPathOutputNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ExecutionPathOutputName");
    if ((data != null))
    {
        this._ExecutionPathOutputNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class BeginTransaction_GenBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
